### ISSUE TITLE
 "comment" icon on tasks in administration panel

### ISSUE THREAD

**Issue by RSCMontreuil** [coopcycle/coopcycle-web#3528]
**In order to** avoid missing customers comments in their commands, and to save time

**As a** dispatcher,

**I want** a "comment" icon to appear on tasks in the administration panel.

**Whereas currently** nothing allows to distinguish the tasks with comments, so dispatch has to be very rigorous and open every tasks one after the order to check this. It is time consuming and it is very easy to miss comments.

**Comment by rayon9coop** [comment]
+1

**Comment by ERAMANrepartos** [comment]
This would be important for both Dispatch in the admin panel and the orders dashboard, as well as for the restaurant in their orders dashboard

**Comment by rayon9coop** [comment]
Perfect! Very niceSerge MignonsinRayon9 - Cyclo-logistiqueLivraisons à vélo-cargo / Stockage urbain / Conseil et consultanceRue de Mulhouse, 36 - 4020 Liège+32 479 589 109En savoir plus sur nos services? www.rayon9.beLe 8 mai 2023 18:04, Lucas Ferraro ***@***.***> a écrit :
Hi!
@RSCMontreuil @rayon9coop @ERAMANrepartos
What do you think about this? As you can see, at the end of the task description if there's comments now we show that 'comment' icon.


@ERAMANrepartos You have mentioned that this would be important for orders dashboards but there we don't show task, we show the order. Do you mean to add the same icon when an order has a note? Or when the tasks in the order has comments?

**Comment by ERAMANrepartos** [comment]
This is great! I would consider giving it a color, though that is maybe something for the UI review. 

As for the orders thing @rayon9coop , I think this feature should be global. In orders the same icon in the same format should appear for a restaurant in the orders dashboard if there is a comment for the kitchen, if there is a a comment for delivery instructions, the icon should show up in the map for a courier, in the task list for a courier, in the admin dashboard for dispatch....etc etc

**Comment by ERAMANrepartos** [comment]
I duplicated this by accident earlier, but I also added some more info for you @lucasferraro 

https://github.com/coopcycle/coopcycle-web/issues/3641

**Comment by alexsegura** [comment]
Fixed in #3683

**Comment by Paul-Eraman-CoopCycle** [comment]
unclosing, it isnt fixed. 3683 has made it in the orders dashboard and panel, but not the admin dashboard

**Comment by lucasferraro** [comment]
Is this duplicated with #3800 ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Yes good catch, closing
